### PR TITLE
Added subscription support

### PR DESCRIPTION
**Pull request by matthewtanner91**
Still requires the latest java API release (with subscription support) to be added to POM of each project. Then, this will all need to be tested.

### CODE REVIEW

**Comment by praves77** [comment]
@matthewtanner91 looks fine.
Any update to [examples-jakarta](https://github.com/Moesif/moesif-servlet/tree/master/examples-jakarta)? We've two frameworks - tomcat and undertow

Please wait for `15` minutes after merging api-java before merging it. It takes about a few minutes to build but JAR becomes available on maven repo in ~10-15 minutes.

**Comment by matthewtanner91** [comment]
> @matthewtanner91 looks fine. Any update to [examples-jakarta](https://github.com/Moesif/moesif-servlet/tree/master/examples-jakarta)? We've two frameworks - tomcat and undertow
> 
> Please wait for `15` minutes after merging api-java before merging it. It takes about a few minutes to build but JAR becomes available on maven repo in ~10-15 minutes.

will look at this now before we merge.

**Comment by matthewtanner91** [comment]
@praves77 anywhere that UpdateCompany was used also has the additional logic for Subscriptions. I see some changes in the Jakarta projects. IS there anything specific you see missing I can fill in before we merge?

**Comment by praves77** [comment]
nvm.. updateSubscription controller was added too.

**Review by praves77 — APPROVED** [review]

**Pull request merged**
